"""add purchase_rate and selling_rate columns

Revision ID: 00392292c1db
Revises: 
Create Date: 2025-10-05 21:06:00.807667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00392292c1db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purchase_rate', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('purchase_rate')

    # ### end Alembic commands ###
