"""Remove purchase_rate and selling_rate

Revision ID: 228bb6f989a3
Revises: 36fdabbaf212
Create Date: 2025-10-06 15:12:39.324993

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '228bb6f989a3'
down_revision = '36fdabbaf212'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_column('purchase_rate')
        batch_op.drop_column('selling_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selling_rate', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('purchase_rate', mysql.FLOAT(), nullable=False))

    # ### end Alembic commands ###
