"""updated item table constrints

Revision ID: 36fdabbaf212
Revises: 429a5c752f70
Create Date: 2025-10-06 02:00:22.593716

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '36fdabbaf212'
down_revision = '429a5c752f70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.alter_column('item_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               nullable=False)
        batch_op.alter_column('purchase_rate',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.alter_column('selling_rate',
               existing_type=mysql.FLOAT(),
               nullable=False)
        batch_op.create_unique_constraint(None, ['item_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('selling_rate',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('purchase_rate',
               existing_type=mysql.FLOAT(),
               nullable=True)
        batch_op.alter_column('item_name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               nullable=True)

    # ### end Alembic commands ###
