"""add foreign keys and constraints

Revision ID: 8cc083f05c89
Revises: 228bb6f989a3
Create Date: 2025-10-09 13:10:05.744010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8cc083f05c89'
down_revision = '228bb6f989a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('item_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('qty',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('rate',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_purchase_item_id'), ['item_id'], unique=False)
        batch_op.create_foreign_key(None, 'item', ['item_id'], ['item_id'])

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.alter_column('item_id',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('qty',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.alter_column('rate',
               existing_type=mysql.INTEGER(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_sales_item_id'), ['item_id'], unique=False)
        batch_op.create_foreign_key(None, 'item', ['item_id'], ['item_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_item_id'))
        batch_op.alter_column('rate',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('qty',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('item_id',
               existing_type=mysql.INTEGER(),
               nullable=True)

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_purchase_item_id'))
        batch_op.alter_column('rate',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('qty',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('item_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###
