"""Add ON DELETE CASCADE to foreign keys

Revision ID: b917e93f1d06
Revises: 8cc083f05c89
Create Date: 2025-10-17 13:05:37.307128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b917e93f1d06'
down_revision = '8cc083f05c89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('purchase_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'item', ['item_id'], ['item_id'], ondelete='CASCADE')

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('sales_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'item', ['item_id'], ['item_id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('sales_ibfk_1'), 'item', ['item_id'], ['item_id'])

    with op.batch_alter_table('purchase', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('purchase_ibfk_1'), 'item', ['item_id'], ['item_id'])

    # ### end Alembic commands ###
